FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;
using System.Web.Services.Description;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        [HttpPost]
        public JsonResult Incluir(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                string cpfSemPontuacao = model.Cpf.Replace(".", "").Replace("-", "");
                var cpfJaExiste = bo.VerificarExistencia(cpfSemPontuacao, model.Id);
                if (cpfJaExiste)
                {
                    return Json(new { Result = "ERRO", Message = "O Cpf informado já foi vinculado a um beneficiário. Favor informar outro Cpf." });
                }

                model.Id = bo.Incluir(new Beneficiario()
                {
                    Nome = model.Nome,
                    Cpf = cpfSemPontuacao,
                    IdCliente = model.IdCliente,
                });


                return Json(new { Result = "OK", Message = "Cadastro efetuado com sucesso." });
            }
        }

        [HttpPost]
        public JsonResult Alterar(BeneficiarioModel model)
        {
            BoBeneficiario bo = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                string cpfSemPontuacao = model.Cpf.Replace(".", "").Replace("-", "");
                var cpfJaExiste = bo.VerificarExistencia(cpfSemPontuacao, model.Id);
                if (cpfJaExiste)
                {
                    return Json(new { Result = "ERROR", Message = "O Cpf informado já foi vinculado a um beneficiário. Favor informar outro Cpf."});
                }
                bo.Alterar(new Beneficiario()
                {
                    Id = model.Id,
                    Nome = model.Nome,
                    Cpf = cpfSemPontuacao
                });

                return Json(new { Result = "OK", Message = "Cadastro alterado com sucesso." });
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoBeneficiario bo = new BoBeneficiario();
            Beneficiario beneficiario = bo.Consultar(id);
            BeneficiarioModel model = null;

            if (beneficiario != null)
            {
                model = new BeneficiarioModel()
                {
                    Id = beneficiario.Id,
                    Nome = beneficiario.Nome,
                    Cpf = beneficiario.Cpf
                };


            }

            return View(model);
        }

        [HttpPost]
        public JsonResult Excluir(long id)
        {
            BoBeneficiario bo = new BoBeneficiario();

            bo.Excluir(id);

            return Json(new { Result = "OK", Message = "Cadastro excluído com sucesso." });

        }

        [HttpGet]
        public JsonResult BeneficiarioList(long idCliente)
        {
            try
            {
                List<Beneficiario> listaAtualizada = new List<Beneficiario>();
                var beneficiarios = new BoBeneficiario().Pesquisa(idCliente);
                foreach (var item in beneficiarios)
                {
                    item.Cpf = Convert.ToUInt64(item.Cpf).ToString(@"000\.000\.000\-00");
                    listaAtualizada.Add(item);
                }

                //Return result
                return Json(new { Result = "OK", BeneficiarioList = listaAtualizada }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            BoCliente bo = new BoCliente();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                string cpfSemPontuacao = model.Cpf.Replace(".", "").Replace("-", "");
                var cpfJaExiste = bo.VerificarExistencia(cpfSemPontuacao, model.Id);
                if (cpfJaExiste)
                {
                    return Json(new { Result = "ERROR", Message = "O Cpf informado já foi vinculado a um cliente. Favor informar outro Cpf." });
                }
                model.Id = bo.Incluir(new Cliente()
                {
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    Cpf = cpfSemPontuacao
                });


                return Json(new { Result = "OK", Message = "Cadastro alterado com sucesso." });
            }
        }

        [HttpPost]
        public JsonResult Alterar(ClienteModel model)
        {
            BoCliente bo = new BoCliente();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else
            {
                string cpfSemPontuacao = model.Cpf.Replace(".", "").Replace("-", "");
                var cpfJaExiste = bo.VerificarExistencia(cpfSemPontuacao, model.Id);
                if (cpfJaExiste)
                {
                    return Json(new { Result = "ERROR", Message = "O Cpf informado já foi vinculado a um cliente. Favor informar outro Cpf." });
                }
                bo.Alterar(new Cliente()
                {
                    Id = model.Id,
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    Cpf = cpfSemPontuacao
                });

                return Json(new { Result = "OK", Message = "Cadastro alterado com sucesso." });
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente bo = new BoCliente();
            Cliente cliente = bo.Consultar(id);
            Models.ClienteModel model = null;

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone,
                    Cpf = cliente.Cpf
                };


            }

            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel
@{
    ViewBag.Title = "Alterar Cliente";
}
@section scripts{
    <script>
        //clientes
        var urlPost = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';

        //beneficiarios
        var urlAlteracaoBeneficiario = '@Url.Action("Alterar", "Beneficiario", new { area = "" })';
        var urlExcluirBeneficiario = '@Url.Action("Excluir", "Beneficiario", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/altClientes")
    @Scripts.Render("~/bundles/beneficiarios")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")
@Html.Partial("_ModalBeneficiario")

FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
<form id="formCadastro" method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nome">Nome:</label>
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Sobrenome">Sobrenome:</label>
                <input required="required" type="text" class="form-control" id="Sobrenome" name="Sobrenome" placeholder="Ex.: da Silva" maxlength="255">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Cpf">CPF:</label>
                <input required="required" type="text" class="form-control" id="Cpf" name="Cpf" placeholder="Ex.: 999.999.999-99" maxlength="14">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nacionalidade">Nacionalidade:</label>
                <input required="required" type="text" class="form-control" id="Nacionalidade" name="Nacionalidade" placeholder="Ex.: brasileira" maxlength="50">
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="CEP">CEP:</label>
                <input required="required" type="text" class="form-control" id="CEP" name="CEP" placeholder="Ex.: 01011-100" maxlength="9">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Estado">Estado:</label>
                <select required="required" id="Estado" class="form-control" name="Estado">
                    <option value="">Selecione</option>
                    <option value="SP">São Paulo</option>
                    <option value="PE">Pernambuco</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Cidade">Cidade:</label>
                <input required="required" type="text" class="form-control" id="Cidade" name="Cidade" maxlength="50" placeholder="Ex.: São Paulo">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="Logradouro">Logradouro:</label>
                <input required="required" type="text" class="form-control" id="Logradouro" name="Logradouro" placeholder="Ex.: Rua Boa Vista 253" maxlength="500">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Email">E-mail:</label>
                <input required="required" type="text" class="form-control" id="Email" name="Email" placeholder="Ex.: email@email.com" maxlength="2079">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Telefone">Telefone:</label>
                <input required="required" type="tel" class="form-control" id="Telefone" name="Telefone" placeholder="Ex.: (11) 2020-3030" maxlength="15">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="pull-right">
                <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
            </div>
        </div>
    </div>


</form>

FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@{
    ViewBag.Title = "Cadastrar Cliente";
}
@section scripts{
    <script>
        var urlPost = '@Url.Action("Incluir", "Cliente", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/clientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}
@section scripts{
<script>
    var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
    var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';

</script>
    @Scripts.Render("~/bundles/listClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class= "btn btn-sm btn-primary pull-right" })
<table id="gridClientes" class="table"></table>

FI.WebAtividadeEntrevista/Views/Cliente/_ModalBeneficiario.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel

<button type="button" onclick="modalBeneficiarios(@Model.Id)" class="btn btn-primary" data-toggle="modal" data-target=".modal-lg">
    Beneficiários
</button>

<div class="modal fade modal-lg" id="modalBeneficiario" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-modal="true" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Beneficiários</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    <input type="hidden" id="idCliente" value="@Model.Id" name="IdCliente" />
                    <div class="row visualizarBeneficiario">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="Cpf">CPF:</label>
                                <input required="required" id="CpfBeneficiario" type="text" class="form-control" name="Cpf" placeholder="Ex.: 999.999.999-99" maxlength="14">
                                <span asp-validation-for="@Model.Cpf" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="Nome">Nome:</label>
                                <input required="required" type="text" class="form-control" id="NomeBeneficiario" name="Nome" placeholder="Ex.: João" maxlength="50">
                                <span asp-validation-for="@Model.Nome" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <button type="submit" class="btn btn-sm btn-success incluir" style="margin-top: 26px;">Incluir</button>
                            </div>
                        </div>
                    </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">CPF</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody class="tbody-tabela-modal">
                        <tr id="editar-beneficiario-linhas" hidden>
                            <td class="cpf">
                                <input type="text" id="editarCpfBenef" class="form-control input-cpf" placeholder="Ex.: 999.999.999-99" maxlength="14">
                            </td>
                            <td class="nome">
                                <input type="text" class="form-control input-nome" placeholder="Ex.: João" maxlength="50">
                            </td>
                            <td>
                                <div>
                                    <button class="btn btn-sm btn-danger cancelar">Cancelar</button>
                                    <button class="btn btn-sm btn-success atualizar">Salvar</button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>